version: "3"

services:
  database:
    image: mysql:5.5.57
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  portail:
    image: php:7.2-apache
    ports:
      - "1006:80"
    depends_on:
      - database
    volumes:
      - .:/var/www/html
      - ./config/apache/vhost.conf:/etc/apache2/vhosts/site-enabled/vhost.conf
