version: "3"

services:
  website:
    image: nicolashefti/symfony-crud
    ports:
      - "1006:80"
    volumes:
      - .:/var/www/html
      - ./config/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
